# Generated by Django 6.0.3 on 2026-04-01 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('salary_range', models.CharField(max_length=100)),
                ('application_link', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='has_active_subscription',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='membership',
            field=models.CharField(choices=[('basic', 'Basic'), ('premium', 'Premium')], default='basic', max_length=10),
        ),
    ]
